### ISSUE TITLE
Template cleanup workflow removes Amper plugin from settings.gradle.kts

### ISSUE THREAD

**Issue by Syex** [kotlin-hands-on/advent-of-code-kotlin-template-amper#1]
Hi,

I've just used your template and had issues running the generated project. From Fleet 1.27 there was no option to run the project.

The [commit](https://github.com/Syex/AdventOfCode-2023/commit/6130465dec7c6f22adabd69ce3872895e8d8b8b3) run by your template cleanup action [removed the Amper plugin](https://github.com/Syex/AdventOfCode-2023/commit/6130465dec7c6f22adabd69ce3872895e8d8b8b3#diff-5625e3601fa0ad3a6a2824239e5a2fde71c149597d31394f9224a08c24be7b9dL3) from the project, hence I could't run it.

After [restoring the plugin application](https://github.com/Syex/AdventOfCode-2023/commit/c56a3f72324b62f3df387d62a4f6bc6cb5eacde0) it seems to work as expected now.

Edit: Sorry the workflow is not removing the plugin, but simply [misses](https://github.com/kotlin-hands-on/advent-of-code-kotlin-template-amper/blob/main/.github/template-cleanup/settings.gradle.kts) the code to apply it and hence it gets deleted when the workflow [moves](https://github.com/kotlin-hands-on/advent-of-code-kotlin-template-amper/blob/main/.github/workflows/template-cleanup.yml#L45) the template files.

**Comment by hsz** [comment]
Thanks for spotting, Tom!
